### ISSUE TITLE
Use markdown style link in README.

### ISSUE THREAD

**Issue by fernvenue** [bdim404/HackerNews-Summarize-Telegram-Bot#5]
I just found the link in README is not markdown style:

> This is a bot used with this Hacker News Feed Telegram chnnel(https://t.me/hacker_news_feed) ,forword the message to the bot and return the summarize to you.

Maybe it will be better to use standard markdown format?

**Comment by bdim404** [comment]
https://github.com/bdim404/HackerNews-Summarize-Telegram-Bot/pull/6
